"""Subset Open Runde Bold to the byot wordmark glyphs and write src/wordmark-font.ts.

Run from web/: uv run --with fonttools --with brotli scripts/build-wordmark-font.py
"""
import base64
import io
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

WEB = Path(__file__).resolve().parent.parent
SOURCE = WEB.parent / "Sources/Resources/Fonts/OpenRunde-Bold.otf"

font = TTFont(SOURCE)
options = subset.Options()
options.flavor = "woff2"
options.layout_features = ["kern"]
options.name_IDs = ["*"]
subsetter = subset.Subsetter(options)
subsetter.populate(text="byot")
subsetter.subset(font)
out = io.BytesIO()
font.flavor = "woff2"
font.save(out)
data = base64.b64encode(out.getvalue()).decode()

(WEB / "src/wordmark-font.ts").write_text(
    "// Generated by scripts/build-wordmark-font.py. Open Runde Bold by Laurids Kern,\n"
    "// SIL Open Font License 1.1, subset to the glyphs of the byot wordmark.\n"
    f'export const WORDMARK_FONT = `@font-face {{ font-family: "Open Runde"; font-weight: 700; font-display: block; src: url(data:font/woff2;base64,{data}) format("woff2"); }}`;\n'
)
print(len(out.getvalue()), "bytes")
