"""Bundle Latin subsets of the same Open Runde fonts used by the iOS app.

Run from web/: uv run --with fonttools --with brotli scripts/build-fonts.py
The OFL license is included in the generated module and in the page source.
"""

from base64 import b64encode
from io import BytesIO
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

web = Path(__file__).resolve().parents[1]
fonts = web.parent / "Sources/Resources/Fonts"
license_text = (fonts / "OpenRunde-LICENSE.txt").read_text()
rules = []
for weight, name in [(400, "Regular"), (600, "Semibold")]:
    font = TTFont(fonts / f"OpenRunde-{name}.otf")
    font.recalcTimestamp = False
    options = subset.Options()
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=list(range(0x20, 0x100)) + list(range(0x2000, 0x2070)))
    subsetter.subset(font)
    font.flavor = "woff2"
    output = BytesIO()
    font.save(output)
    encoded = b64encode(output.getvalue()).decode()
    rules.append(
        f'@font-face {{ font-family: "Open Runde"; font-style: normal; '
        f'font-weight: {weight}; font-display: swap; '
        f'src: url(data:font/woff2;base64,{encoded}) format("woff2"); }}'
    )

(web / "src/fonts.ts").write_text(
    "// Generated by scripts/build-fonts.py. Do not edit the font data.\n"
    + "export const FONT_STYLES = `/*\n" + license_text + "\n*/\n"
    + "\n".join(rules) + "`;\n"
)
print("Bundled Open Runde Regular and Semibold with their OFL license.")
