const content: Record<string, {title:string; body:string}> = {
  '/privacy': {
    title:'Privacy policy',
    body:`<p>This policy covers the BYOT iOS app. BYOT connects to the OpenCode servers you configure. There is no BYOT account, advertising, or analytics SDK.</p>
<h2>Your OpenCode content</h2><p>Prompts, transcripts, source code, files, and tool output travel directly between your iPhone and your configured OpenCode server. Server passwords are stored in the iOS Keychain and sent only to that server. Model providers configured on your server handle your content under their own policies.</p>
<h2>Optional push notifications</h2><p>Starting with version 1.0.26, you can opt in to notifications and pair a companion on your OpenCode computer. The BYOT relay, hosted by Cloudflare, stores an Apple push device token, random subscription and saved-server identifiers, hashed authentication tokens, notification preferences, muted-session hashes, and connection timestamps. It uses these only to provide notifications.</p>
<p>The companion sends the alert category, timestamp, a deduplication identifier, a hashed session identifier, and an encrypted route identifying the session to open. Alert text is generic. Prompts, code, session titles, your server address, and your server password are not sent to the relay or included in Apple notifications. Your server credentials stay in an owner-readable file on your computer.</p>
<p>The route key passes through the relay during pairing. A pairing code expires after 10 minutes. The key is cleared from the active database when pairing completes; expired pairing data is cleared by hourly maintenance. Notification routes are encrypted during delivery, but this is not a claim that the relay can never access route metadata. Apple processes the device token and notification payload to deliver alerts.</p>
<h2>Retention and controls</h2><p>Delivery deduplication records expire after 24 hours and are removed by hourly maintenance. Unpaired registrations expire after 24 hours. Paired registrations remain until you disconnect notifications or remove the saved server in BYOT. Those actions delete the active subscription and its delivery records. Cloudflare may retain infrastructure backups and operational request metadata under its service policies. Notification bodies and credentials are not written to application logs.</p>
<p>You can disable all notifications, disable individual categories, mute sessions, or disconnect the companion in BYOT. iOS Settings also controls notification permission. Removing the app alone does not immediately delete a relay registration or guarantee deletion of Keychain items. Disconnect notifications before uninstalling if you want to revoke the companion immediately.</p>
<h2>Local storage</h2><p>Connection profiles and display preferences are stored on your iPhone. Passwords and notification credentials are stored in Keychain. The companion stores its configuration and a bounded, one-hour retry queue locally on your computer.</p>
<h2>Children and contact</h2><p>BYOT is a developer tool and is not directed at children. For privacy questions, <a href="https://github.com/steventsao/byot/issues">open an issue</a> without including passwords or private content. Changes to this policy will be posted here.</p>`
  },
  '/support': {
    title:'Setup and support',
    body:`<p>BYOT is a native iOS client for <a href="https://opencode.ai">OpenCode</a>. Run OpenCode on your computer, expose it to your iPhone over trusted HTTPS with Basic authentication, then add the server in BYOT. A private network such as Tailscale is a common way to reach your computer.</p>
<h2>Connect your server</h2><ol><li>Start your OpenCode server with a password and a trusted HTTPS endpoint.</li><li>In BYOT, choose Add server and enter its URL, username, and password.</li><li>Test the connection and save. Open a session or create one with New session.</li></ol>
<h2>Background notifications (1.0.26+)</h2><ol><li>Open the server menu, choose Notifications, and tap Set up notifications. Allow iOS notifications.</li><li>Copy the setup command from BYOT and run it on the OpenCode computer. Node.js 22 or later is required.</li><li>Enter the pairing code and your OpenCode address and password in that terminal. The password remains on that computer. Localhost HTTP is supported for a companion on the same machine; remote connections require HTTPS.</li><li>On macOS, accept background startup to keep the companion running after login. On other systems, keep the displayed run command active or use your own service manager.</li><li>Tap Check connection and Send test notification in BYOT. Start an OpenCode turn, put BYOT in the background, and tap an alert to reopen the session.</li></ol>
<p>You can select approval, question, completion, and error alerts, or mute a session from its menu. Alerts do not approve requests automatically. Pairing another companion replaces the previous companion for that iPhone and server. Other iPhones pair separately.</p>
<h2>Troubleshooting</h2><ul><li>No alert: check iOS notification settings and Focus, BYOT category settings, session mute, and the companion’s Last connected time. The OpenCode computer and companion must remain awake and connected.</li><li>Server unavailable: verify the HTTPS address and password and the phone’s private-network connection.</li><li>Session missing: a notification may refer to a deleted session. Open the session list to refresh it.</li><li>Companion reconnecting: verify its local OpenCode address and password, then run setup again if they changed.</li></ul>
<p>Events that occur while the companion is stopped or disconnected from OpenCode may be missed; the upstream event stream is not a durable inbox. Captured alerts retry for up to one hour. Apple delivery and Focus settings can delay notifications. Debug builds require a separate sandbox APNs key; TestFlight uses production APNs.</p>
<h2>Privacy and help</h2><p>OpenCode content remains between your phone and your server. Optional notifications use a BYOT relay and Apple push delivery; see the <a href="/privacy">privacy policy</a>. For help, <a href="https://github.com/steventsao/byot/issues">open an issue</a>.</p>`
  }
};
export function renderInformation(path:string):string|undefined {
  const page=content[path];if(!page)return;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title} — BYOT</title><style>body{font:17px/1.6 system-ui,sans-serif;color:#202524;background:#fafbf8;max-width:760px;padding:32px 22px;margin:auto}a{color:#286653}h1{font-size:2rem}h2{font-size:1.25rem;margin-top:2rem}li{margin:.5rem 0}footer{color:#58615d;margin-top:3rem;font-size:.9rem}</style></head><body><nav><a href="/">byot</a></nav><main><h1>${page.title}</h1>${page.body}</main><footer>Updated September 19, 2026</footer></body></html>`;
}
