/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4d6f13abf0b5d76fb6aa6b992bae6caa)
interface __BaseEnv_Env {
	DB: D1Database;
	QUEUE_RATE_LIMITER: RateLimit;
	RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APNS_TEAM_ID: "449BD89VDV";
	APNS_TOPIC: "com.steventsao.byot";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APNS_TEAM_ID" | "APNS_TOPIC">> {}
}
